Install 'Faker' instead of deprecated 'fake-factory'
Foreign requirement 'fake-factory' was deprecated in favor of 'Faker'. Update the list of requirements to reflect this change.

Fixes ImportError upon running stdg after installing.

    ImportError: The ``fake-factory`` package is now called ``Faker``.